import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import mongoDBConnection from '../db.config/db.config'
import { Toaster } from 'react-hot-toast'


const inter = Inter({ subsets: ['latin'] })

// Initialize MongoDB connection
mongoDBConnection();

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <Toaster position='top-right' /> 
       
        {children}</body>
    </html>
  )
}
